#!/bin/sh

set -e

which -s brew || (echo "Homebrew is required: http://brew.sh/" && exit 1)

brew bundle check || brew bundle

# Disable Dock icon for Hammerspoon
defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool FALSE

# If Hammerspoon is already running, kill it so we can pick up the new config
# when opening Hammerspoon below
killall Hammerspoon || true

# Open Apps
open /Applications/Hammerspoon.app
open /Applications/Karabiner-Elements.app

# Enable apps at startup
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:true}' > /dev/null
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Karabiner-Elements.app", hidden:true}' > /dev/null

echo "Done! Remember to enable Accessibility for Hammerspoon."
