require "plugins.enhancements.copilot"
require "plugins.enhancements.gps"
require "plugins.enhancements.impatient"
require "plugins.enhancements.neoscroll"
require "plugins.enhancements.project"
-- require "plugins.enhancements.session-manager"
require "plugins.enhancements.sniprun"
require "plugins.enhancements.spectre"
