require "user.settings"
require "user.keymaps"
require "user.autocommands"
require "user.colorscheme"
require "user.functions"
require "user.symbol-outline"
require "user.registers"

require "plugins.editing-text"
require "plugins.git"
require "plugins.visual-tools"
require "plugins.enhancements"
