#!/usr/bin/env zsh

brew services stop yabai

brew upgrade yabai

# reconfigure the scripting addition again
sudo bash -c "cat <<EOF > /private/etc/sudoers.d/yabai
$(whoami) ALL = (root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai)) --load-sa
EOF"

# check System Integrity Protection
csrutil status

# load scripting addition
sudo $(which yabai) --load-sa

# finally, start yabai
brew services start yabai
