#!/usr/bin/env bash

# ====== Scripting Addition ====================

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action ="sudo yabai --load-sa"

# ====== Variables =============================

padding="10"
gaps="10"

normal_border_color="010101"
focused_border_color="1e96ff"
preselect_border_color="2d74da"

center=3:6:1:1:4:1
top_right=3:3:2:0:1:1

# ====== Tiling settings =======================

yabai -m config layout                      bsp
yabai -m config window_placement            second_child
yabai -m config auto_balance                on
yabai -m config split_ratio                 0.5

yabai -m config top_padding                 "${padding}"
yabai -m config bottom_padding              "${padding}"
yabai -m config left_padding                "${padding}"
yabai -m config right_padding               "${padding}"
yabai -m config window_gap                  "${gaps}"

yabai -m config window_topmost              on
yabai -m config window_shadow               float

yabai -m config window_opacity              on
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.7

yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

# ====== Border settings =======================

yabai -m config window_border               off
yabai -m config window_border_width         10
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== List of rules =========================

yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off border=off sticky=on grid=${center}
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Harvest" app="^Harvest$" border=off manage=off sticky=on grid=${top_right}
yabai -m rule --add label="Simulator" app="^Simulator$" manage=off border=off sticky=on opacity=1
yabai -m rule --add label="Bartender" app="^Bartender" manage=off border=off
