#!/usr/bin/env bash

# ====== Scripting Addition ====================

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ====== Load Configuration Files  =============

find "${HOME}/.config/yabai/config" -type f -perm +111 -exec {} \;

# ====== Restore Windows =============

# source ./scripts/store_window.sh
