#!/usr/bin/env zsh

yabai -m config layout                      bsp
yabai -m config window_placement            second_child
yabai -m config auto_balance                on
yabai -m config split_ratio                 0.5

yabai -m config window_topmost              on
yabai -m config window_shadow               float


# ====== Padding =======================

value=10

yabai -m config top_padding                 ${value}
yabai -m config bottom_padding              ${value}
yabai -m config left_padding                ${value}
yabai -m config right_padding               ${value}
yabai -m config window_gap                  ${value}

# ====== Opacity =======================

yabai -m config window_opacity              off
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.7

# ====== Mouse =======================

yabai -m config mouse_modifier              alt
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

# ====== Border =======================

normal_border_color="010101"
focused_border_color="1e96ff"
preselect_border_color="2d74da"

yabai -m config window_border               off
yabai -m config window_border_width         10
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"
