#!/usr/bin/env bash


PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:${PATH}"
export PATH

export PATH="/Users/steve/.bun/bin:$PATH"

eval "$(/opt/homebrew/bin/brew shellenv)"

eval "$(zoxide init zsh)"

# Added by OrbStack: command-line tools and integration
source ~/.orbstack/shell/init.zsh 2>/dev/null || :
