#!/usr/bin/env bash

# Configure home directory
export ZDOTDIR=$HOME/.config/zsh
# Add homebrew binaries
export PATH="/usr/local/bin:$PATH"

# export SSH_AUTH_SOCK=~/.1password/agent.sock
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
