#!/usr/bin/env bash

#       ______   ______   __  __   ______   ______
#      /\___  \ /\  ___\ /\ \_\ \ /\  == \ /\  ___\
#   ___\/_/  /__\ \___  \\ \  __ \\ \  __< \ \ \____
#  /\__\ /\_____\\/\_____\\ \_\ \_\\ \_\ \_\\ \_____\
#  \/__/ \/_____/ \/_____/ \/_/\/_/ \/_/ /_/ \/_____/
#


export ZPLUG_HOME=$(brew --prefix)/opt/zplug

source $ZPLUG_HOME/init.zsh
zplug "agkozak/zsh-z"
# zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
zplug 'mafredri/zsh-async'
zplug 'zsh-users/zsh-syntax-highlighting'
zplug 'zsh-users/zsh-completions'
zplug load

for zsh_source in $HOME/.dot-files/zsh/config/*.sh; do
    source $zsh_source
done
